### ISSUE TITLE
[1.6.0] Dedicated server crash on load

### ISSUE THREAD

**Issue by jpastuszek** [NovaViper/ZeroQuest#13]
When I put ZeroQuest v1.6.0  on dedicated server (server.jar) the game crashes on load with java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX:

https://gist.github.com/jpastuszek/ca06b1989a7627f2a481

**Comment by NovaViper** [comment]
I just fixed it in 2e38643
